---
ansible_python_interpreter: /usr/bin/python3
ansible_user: vagrant
ansible_password: "{{ vault_ansible_password }}"
ansible_ssh_private_key_file: "{{ vault_ansible_ssh_private_key_file }}"
ansible_become_user: root
ansible_become_password: "{{ vault_ansible_become_password }}"
ansible_connection: ssh
